In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
print(data)

[[-0.42440332 -1.23644884  0.24071192]
 [-0.48362774  0.56419543  1.17287323]]


In [3]:
print("\nMultiplica todo o conteúdo por 14")
print(data * 14)


Multiplica todo o conteúdo por 14
[[ -5.9416465  -17.31028382   3.36996694]
 [ -6.77078835   7.89873595  16.42022528]]


In [4]:
print("\nRealiza a soma elemento a elemento da matriz")
print(data + data)


Realiza a soma elemento a elemento da matriz
[[-0.84880664 -2.47289769  0.48142385]
 [-0.96725548  1.12839085  2.34574647]]


In [5]:
print(data.shape) #Exibe a forma do ndarray. Nº de linhas e Nº de colunas, respectivamente

(2, 3)


In [6]:
print(data.dtype) #Exibe o tipo dos dados armazenados

float64


In [7]:
print(data.ndim) #Exibe o número de dimensões da estrutura

2


In [8]:
lista1 = [6, 7.5, 8, 0, 1] #Uma lista do Python

In [9]:
array1 = np.array(lista1) #O método array da biblioteca Numpy é responsável pela criação

In [10]:
print(array1)
print(type(array1))
print(array1.ndim)
print(array1.shape)
print(array1.dtype)

[6.  7.5 8.  0.  1. ]
<class 'numpy.ndarray'>
1
(5,)
float64


In [11]:
lista2 = [[1, 2, 3, 4], [5, 6, 7, 8]] #Lista Python com duas dimensões
array2 = np.array(lista2)
#Analise os atributos da nova lista criada

In [12]:
g = np.arange(24)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [14]:
g.reshape(4,6)
print(g.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [15]:
g.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
g = g.reshape(2, 3, 4)
g

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
g.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Operações Matemáticas

In [19]:
array3 = np.array([[1., 2., 3.,], [4., 5., 6.]])

In [20]:
print(array3)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
array3 * array3

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [22]:
array3 - array3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
1 / array3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [24]:
array4 = np.array([[0., 4., 1.], 
                   [7., 2., 12.]])
print(array4 > array3)

[[False  True False]
 [ True False  True]]


In [25]:
print(array4[array4 > array3])

[ 4.  7. 12.]


# Indexação e Fatiamento

In [26]:
array5 = np.arange(10)
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array5[5]

5

In [29]:
array5[2]

2

In [30]:
array5[5:8]

array([5, 6, 7])

In [31]:
array5[::2]

array([0, 2, 4, 6, 8])

In [32]:
array5[5:8] = 154

In [33]:
array5

array([  0,   1,   2,   3,   4, 154, 154, 154,   8,   9])

In [34]:
arr_slice = array5[5:8]
arr_slice

array([154, 154, 154])

In [35]:
arr_slice[1] = 12345
arr_slice

array([  154, 12345,   154])

In [36]:
array5

array([    0,     1,     2,     3,     4,   154, 12345,   154,     8,
           9])

In [37]:
arr_slice = array5[5:8].copy()
arr_slice

array([  154, 12345,   154])

In [38]:
arr_slice[2] = 1233

In [39]:
arr_slice

array([  154, 12345,  1233])

In [40]:
array5

array([    0,     1,     2,     3,     4,   154, 12345,   154,     8,
           9])

In [41]:
matriz_bidimensional = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [42]:
matriz_bidimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
matriz_bidimensional[0][1]

2

In [44]:
matriz_bidimensional[0,1]

2

In [50]:
matriz_bidimensional[:,1:2]

array([[2],
       [5],
       [8]])

In [51]:
matriz_bidimensional[1, :2]

array([4, 5])

In [52]:
matriz_bidimensional[0, 2]

3

In [53]:
matriz_bidimensional[:2, 2]

array([3, 6])

In [54]:
matriz_bidimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
matriz_bidimensional[1:,1:]

array([[5, 6],
       [8, 9]])

In [58]:
array5[::-1]

array([    9,     8,   154, 12345,   154,     4,     3,     2,     1,
           0])

In [59]:
nomes = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
nomes

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [60]:
dados = np.random.randn(7, 4)

In [61]:
dados

array([[ 1.27409445, -2.18460174,  0.32279243,  0.09406218],
       [-0.68204831, -0.18041427,  0.22163407, -0.5817092 ],
       [-0.90266554,  0.36494925,  3.16723881, -1.00798406],
       [ 1.12269309,  0.60344578,  0.55289644, -2.16699486],
       [ 0.56224426,  0.15189053, -1.31525299, -0.77908148],
       [ 0.41658155,  0.11697455, -0.00975531,  0.13766441],
       [-1.50155373,  1.29668794, -1.93016812,  0.1334547 ]])

In [62]:
nomes == 'Bob'

array([ True, False, False,  True, False, False, False])

In [63]:
dados[nomes == 'Bob']

array([[ 1.27409445, -2.18460174,  0.32279243,  0.09406218],
       [ 1.12269309,  0.60344578,  0.55289644, -2.16699486]])

In [64]:
dados[~(nomes == 'Bob')]

array([[-0.68204831, -0.18041427,  0.22163407, -0.5817092 ],
       [-0.90266554,  0.36494925,  3.16723881, -1.00798406],
       [ 0.56224426,  0.15189053, -1.31525299, -0.77908148],
       [ 0.41658155,  0.11697455, -0.00975531,  0.13766441],
       [-1.50155373,  1.29668794, -1.93016812,  0.1334547 ]])

In [65]:
dados[nomes != 'Bob']

array([[-0.68204831, -0.18041427,  0.22163407, -0.5817092 ],
       [-0.90266554,  0.36494925,  3.16723881, -1.00798406],
       [ 0.56224426,  0.15189053, -1.31525299, -0.77908148],
       [ 0.41658155,  0.11697455, -0.00975531,  0.13766441],
       [-1.50155373,  1.29668794, -1.93016812,  0.1334547 ]])

In [66]:
mascara = (nomes == 'Bob') | (nomes == 'Will')
mascara

array([ True, False,  True,  True,  True, False, False])

In [67]:
nomes

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [68]:
nomes[mascara]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

In [69]:
dados[mascara]

array([[ 1.27409445, -2.18460174,  0.32279243,  0.09406218],
       [-0.90266554,  0.36494925,  3.16723881, -1.00798406],
       [ 1.12269309,  0.60344578,  0.55289644, -2.16699486],
       [ 0.56224426,  0.15189053, -1.31525299, -0.77908148]])

In [70]:
array6 = np.empty((8,4))
array6

array([[1.16900088e-311, 1.16900090e-311, 1.16900090e-311,
        1.16900102e-311],
       [1.16900102e-311, 1.16900102e-311, 1.16900102e-311,
        1.16900102e-311],
       [1.16900102e-311, 1.16900102e-311, 1.16900102e-311,
        1.16900102e-311],
       [1.16900089e-311, 1.16900089e-311, 1.16900089e-311,
        1.16900089e-311],
       [1.16900089e-311, 1.16900089e-311, 1.16900089e-311,
        1.16900089e-311],
       [1.16900089e-311, 1.16900089e-311, 1.16900089e-311,
        1.16900089e-311],
       [1.16900089e-311, 1.16900089e-311, 1.16900545e-311,
        1.16900545e-311],
       [1.16900545e-311, 2.59027896e-144, 7.79952704e-143,
        5.81186265e+294]])

In [71]:
for i in range(8):
    array6[i] = i

In [72]:
array6

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [73]:
array6[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [74]:
array6[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

# Funções Universais

In [75]:
matriz1 = np.random.randn(8,3)
matriz2 = np.random.randn(8,3)
matriz1

array([[-0.92989013, -0.01991525,  0.77699406],
       [ 0.66063456,  0.05762352, -0.82470596],
       [ 1.91661806,  0.43266723,  0.94903818],
       [-0.07934995, -0.29779513,  1.03507797],
       [-0.35817757,  0.23086954,  0.50568862],
       [-0.50830271,  0.82710097, -0.16538149],
       [-0.64514033,  0.51386892,  0.89506163],
       [-0.56428183,  0.64253207,  0.15240693]])

In [76]:
matriz2

array([[ 1.79468229, -0.21106562, -0.95676896],
       [ 0.15223452, -0.18113932, -0.81374119],
       [-0.75395485, -0.45668616, -1.0063243 ],
       [-1.10828606,  0.75526672, -1.67712743],
       [-2.46268379, -1.11523789,  1.25357563],
       [ 0.52481571,  0.90079003, -0.26726385],
       [-0.69006601, -0.32532923,  0.80284329],
       [-1.10484972, -0.89426287, -0.19025416]])

In [77]:
np.add(matriz1, matriz2)

array([[ 0.86479216, -0.23098088, -0.17977491],
       [ 0.81286908, -0.1235158 , -1.63844715],
       [ 1.16266321, -0.02401893, -0.05728612],
       [-1.187636  ,  0.45747159, -0.64204946],
       [-2.82086136, -0.88436835,  1.75926426],
       [ 0.016513  ,  1.72789101, -0.43264533],
       [-1.33520634,  0.18853969,  1.69790493],
       [-1.66913155, -0.25173079, -0.03784724]])

In [78]:
matriz2.T

array([[ 1.79468229,  0.15223452, -0.75395485, -1.10828606, -2.46268379,
         0.52481571, -0.69006601, -1.10484972],
       [-0.21106562, -0.18113932, -0.45668616,  0.75526672, -1.11523789,
         0.90079003, -0.32532923, -0.89426287],
       [-0.95676896, -0.81374119, -1.0063243 , -1.67712743,  1.25357563,
        -0.26726385,  0.80284329, -0.19025416]])

In [79]:
np.matmul(matriz1, matriz2.T)

array([[-2.40805772, -0.77022601, -0.07171781, -0.28757511,  3.28625641,
        -0.71362283,  1.27196905,  0.89737197],
       [ 1.96251986,  0.76123071,  0.30551716,  0.69448604, -2.72502925,
         0.61903218, -1.13673772, -0.62452874],
       [ 2.44038903, -0.55886907, -2.5976768 , -3.38903987, -4.01285997,
         1.14197001, -0.70142334, -2.68505163],
       [-1.06988411, -0.80042297, -0.84579893, -1.87292997,  1.82507476,
        -0.58653391,  0.98264357,  0.157049  ],
       [-1.17537074, -0.5078462 , -0.34427197, -0.27677298,  1.25852256,
        -0.11516452,  0.57804627,  0.09306496],
       [-0.92858258, -0.092624  ,  0.17193913,  1.46539247,  0.1220563 ,
         0.52247956, -0.05109312, -0.14658306],
       [-2.12264917, -0.91964301, -0.64899242, -0.39802429,  2.13771798,
        -0.11490939,  0.99660706,  0.08296001],
       [-1.29414125, -0.32631079, -0.02136328,  0.85506294,  0.86412521,
         0.24190965,  0.30271612,  0.019858  ]])

In [80]:
np.negative(matriz1)

array([[ 0.92989013,  0.01991525, -0.77699406],
       [-0.66063456, -0.05762352,  0.82470596],
       [-1.91661806, -0.43266723, -0.94903818],
       [ 0.07934995,  0.29779513, -1.03507797],
       [ 0.35817757, -0.23086954, -0.50568862],
       [ 0.50830271, -0.82710097,  0.16538149],
       [ 0.64514033, -0.51386892, -0.89506163],
       [ 0.56428183, -0.64253207, -0.15240693]])

In [81]:
np.mod(matriz1, matriz2)

array([[ 0.86479216, -0.01991525, -0.17977491],
       [ 0.05169646, -0.1235158 , -0.01096477],
       [-0.34524649, -0.02401893, -0.05728612],
       [-0.07934995,  0.45747159, -0.64204946],
       [-0.35817757, -0.88436835,  0.50568862],
       [ 0.016513  ,  0.82710097, -0.16538149],
       [-0.64514033, -0.13678954,  0.09221834],
       [-0.56428183, -0.25173079, -0.03784724]])

In [82]:
np.absolute(matriz1)

array([[0.92989013, 0.01991525, 0.77699406],
       [0.66063456, 0.05762352, 0.82470596],
       [1.91661806, 0.43266723, 0.94903818],
       [0.07934995, 0.29779513, 1.03507797],
       [0.35817757, 0.23086954, 0.50568862],
       [0.50830271, 0.82710097, 0.16538149],
       [0.64514033, 0.51386892, 0.89506163],
       [0.56428183, 0.64253207, 0.15240693]])

In [83]:
np.rint(matriz1)

array([[-1., -0.,  1.],
       [ 1.,  0., -1.],
       [ 2.,  0.,  1.],
       [-0., -0.,  1.],
       [-0.,  0.,  1.],
       [-1.,  1., -0.],
       [-1.,  1.,  1.],
       [-1.,  1.,  0.]])

# Métodos Estatísticos

In [84]:
renda_ingressantes = np.array([2.90, 2.90, 2.95, 2.95, 3.10, 3.10, 3.15, 
                               3.20, 3.20, 3.25, 3.30, 3.40, 3.45, 3.45, 
                               3.50, 3.65, 3.65, 3.80, 3.90, 3.90, 4.00,
                               5.00, 5.20, 5.50, 6.40])
renda_ingressantes

array([2.9 , 2.9 , 2.95, 2.95, 3.1 , 3.1 , 3.15, 3.2 , 3.2 , 3.25, 3.3 ,
       3.4 , 3.45, 3.45, 3.5 , 3.65, 3.65, 3.8 , 3.9 , 3.9 , 4.  , 5.  ,
       5.2 , 5.5 , 6.4 ])

In [85]:
np.mean(renda_ingressantes)

3.7120000000000006

In [86]:
np.median(renda_ingressantes)

3.45

In [87]:
np.var(renda_ingressantes)

0.767856

In [88]:
np.std(renda_ingressantes)

0.8762739297731047

In [89]:
np.percentile(renda_ingressantes, 25)

3.15

In [90]:
np.quantile(renda_ingressantes, 0.25)

3.15

In [91]:
np.quantile(renda_ingressantes, 0.50)

3.45

In [92]:
np.quantile(renda_ingressantes, 0.75)

3.9

In [93]:
X = np.array([1, 2, 3])
Y = np.array([0, 1, 0.5])

In [94]:
np.corrcoef(X, Y)

array([[1. , 0.5],
       [0.5, 1. ]])

# Ordenação e Unicidade de Elementos

In [95]:
array7 = np.array([2.52, 3.42, 1.85, 2.95, 3.95, 3.78, 3.17, 3.96, 2.97, 2.98,
3.35, 4.23, 3.42, 4.60, 5.24, 3.64, 4.54, 4.81, 1.77, 1.51, 3.08, 2.00])

In [96]:
np.sort(array7)

array([1.51, 1.77, 1.85, 2.  , 2.52, 2.95, 2.97, 2.98, 3.08, 3.17, 3.35,
       3.42, 3.42, 3.64, 3.78, 3.95, 3.96, 4.23, 4.54, 4.6 , 4.81, 5.24])

In [102]:
np.sort??

In [103]:
# Ordem Decrescente
-np.sort(-array7)

array([5.24, 4.81, 4.6 , 4.54, 4.23, 3.96, 3.95, 3.78, 3.64, 3.42, 3.42,
       3.35, 3.17, 3.08, 2.98, 2.97, 2.95, 2.52, 2.  , 1.85, 1.77, 1.51])

In [104]:
matriz = np.array([[1, 4], [3, 1]])
matriz

array([[1, 4],
       [3, 1]])

In [105]:
np.sort(matriz, axis = 1) # Colunas

array([[1, 4],
       [1, 3]])

In [106]:
np.sort(matriz, axis = 0) # Linhas

array([[1, 1],
       [3, 4]])

In [107]:
nomes = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [108]:
np.unique(nomes)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [109]:
numeros = np.array([3, 3, 2, 2, 1, 1, 1, 4, 4])
numeros

array([3, 3, 2, 2, 1, 1, 1, 4, 4])

In [110]:
np.unique(numeros)

array([1, 2, 3, 4])